spring.application.name=greengrub-mcp-server

spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=greengrub-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.stdio.protocol-version=2025-11-25

spring.main.web-application-type=none
spring.main.banner-mode=off

logging.level.root=OFF
logging.file.name=/Users/I528802/Documents/SpringProj/mcp-server/logs/greengrub-mcp-server.log